# _quarto.yml
project:
  type: website

website:
  title: "Amir Alnajjar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analytics.qmd
        text: Data Analytics
    right:
      - icon: github
        href: https://github.com/amir-alnajjar
      - icon: linkedin
        href: https://linkedin.com/in/amir-alnajjar
  page-footer:
    center: "Â© 2025 Amir Alnajjar"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true